; counter with INTERNAL define (define inside a lambda body)
(define (make-counter)
  (define count 0)
  (define (inc) (set! count (+ count 1)) count)
  inc)
(define c (make-counter))
(display (c)) (display " ") (display (c)) (display " ") (display (c)) (newline)
; internal mutual recursion
(define (test n)
  (define (ev? k) (if (= k 0) #t (od? (- k 1))))
  (define (od? k) (if (= k 0) #f (ev? (- k 1))))
  (ev? n))
(display (test 10)) (display " ") (display (test 7)) (newline)
; internal define + shared mutable state across two internal functions
(define (make-pair)
  (define n 100)
  (define (get) n)
  (define (bump) (set! n (+ n 5)))
  (cons get bump))
(define p (make-pair))
((cdr p)) ((cdr p))
(display ((car p))) (newline)
