(import "cas/algres.lisp")
(define LOG (list 'log)) (define EXP (list 'exp (list 0 1)))
(define dl (list (rat-from-poly (list -2)) (rat-zero) (rat-one)))
(define al (list (rat-make (list 1) (list 0 1))))
(display (car (int-prim-rational-alg al dl LOG))) (newline)
(display (int-prim-rational-alg-verify al dl LOG)) (newline)
(define de (list (rat-from-poly (list -2)) (rat-zero) (rat-one)))
(define ae (list (rat-zero) (rat-one)))
(display (int-prim-rational-alg-verify ae de EXP)) (newline)
(define dn (list (rat-from-poly (list 0 -1)) (rat-zero) (rat-one)))
(display (int-prim-rational-alg-elementary? (list (rat-one)) dn LOG)) (newline)
