(define (filter p xs)
  (cond ((null? xs) '())
        ((p (car xs)) (cons (car xs) (filter p (cdr xs))))
        (else (filter p (cdr xs)))))
(define (append xs ys) (if (null? xs) ys (cons (car xs) (append (cdr xs) ys))))
(define (qsort xs)
  (if (null? xs) '()
      (let ((p (car xs)) (rest (cdr xs)))
        (append (qsort (filter (lambda (x) (< x p)) rest))
                (cons p (qsort (filter (lambda (x) (>= x p)) rest)))))))
(display (qsort '(50 28 17 99 4 3 71 35 8 21 64 12 73 41 5 88 19 96 6 100)))
(newline)
(display (qsort '(9 8 7 6 5 4 3 2 1)))
(newline)
(display (qsort '()))
(newline)
(display (qsort '(42)))
(newline)
