#!/usr/bin/env bash
#
# scripts/clean.sh — remove build artefacts and stray junk.
#
# Usage:
#   ./scripts/clean.sh           # standard cleanup
#   ./scripts/clean.sh --deep    # also wipes Nix result symlink + flake.lock
#   ./scripts/clean.sh --dry     # print what would be removed, don't remove
#
# Safe to run from anywhere — resolves the project root from the
# script's own location.

set -euo pipefail

# --- locate project root --------------------------------------------------
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
root=$(cd -- "$script_dir/.." &>/dev/null && pwd)

# --- options --------------------------------------------------------------
dry=0
deep=0
for arg in "$@"; do
  case "$arg" in
    --dry|-n) dry=1 ;;
    --deep)   deep=1 ;;
    -h|--help)
      sed -n '2,/^$/p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "unknown option: $arg" >&2
      exit 2
      ;;
  esac
done

# --- helpers --------------------------------------------------------------
nuke() {
  # Print, then remove unless --dry.
  local target=$1
  if compgen -G "$target" >/dev/null 2>&1; then
    if [[ $dry -eq 1 ]]; then
      printf '  would remove: %s\n' "$target"
    else
      printf '  removing:     %s\n' "$target"
      # shellcheck disable=SC2086
      rm -rf -- $target
    fi
  fi
}

echo "Cleaning $root"
cd "$root"

# --- standard build artefacts --------------------------------------------
echo "[build]"
nuke "build"
nuke "src/*.o"
nuke "src/*.a"
nuke "src/*.so"
nuke "src/*.gch"
nuke "tests/*.o"
nuke "lizard"           # if accidentally produced at the root
nuke "liblizard.a"
nuke "liblizard.so"

# --- profiler / debugger leftovers ---------------------------------------
echo "[profiler / debugger]"
nuke "gmon.out"
nuke "perf.data"
nuke "perf.data.old"
nuke "callgrind.out.*"
nuke "cachegrind.out.*"
nuke "massif.out.*"
nuke "vgcore.*"
nuke "core"
nuke "core.*"

# --- editor / OS junk ----------------------------------------------------
echo "[editor / OS]"
nuke "*~"
nuke "src/*~"
nuke "include/*~"
nuke "tests/*~"
nuke "examples/*~"
nuke "*.swp"
nuke "src/*.swp"
nuke ".#*"
nuke "src/.#*"
nuke "#*#"
nuke "src/#*#"
nuke ".DS_Store"
nuke "src/.DS_Store"

# --- deep cleanup --------------------------------------------------------
if [[ $deep -eq 1 ]]; then
  echo "[deep]"
  nuke "result"           # nix build result symlink
  nuke "result-*"
  nuke "flake.lock"       # nix flake lock — regenerated by 'nix flake update'
  nuke ".direnv"
fi

echo "Done."
